language: node_js
node_js:
  - "7.3"
env:
  - NODE_ENV=testing INTERNAL_PORT=1050
before_script:
  - npm install -g knex grunt-cli
  - for file in ./config/*.default.json; do cp "$file" "${file/.default.json/.json}"; done
  - cp ./config/db.travis.json ./config/db.json
  - mysql -e 'create database mes'
  - knex migrate:latest
  - knex seed:run
services:
  - mysql
cache:
    directories:
        - node_modules
